name: Build Executables

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags
  workflow_dispatch:  # Allows manual triggering

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to the latest version
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller  # Ensure PyInstaller is installed

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --icon=res/appIcon.ico -n anyGIF main.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3  # Updated to the latest version
        with:
          name: anyGIF-windows
          path: dist/anyGIF.exe

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to the latest version
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller  # Ensure PyInstaller is installed

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --icon=res/appIcon.ico -n anyGIF main.py

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3  # Updated to the latest version
        with:
          name: anyGIF-linux
          path: dist/anyGIF
