name: Build anyGIF

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller ffmpeg-python

      - name: Build Windows executable
        run: |
          pyinstaller --onefile --windowed --icon=res/appIcon.ico --collect-all ffmpeg-python -n anyGIF main.py

      - name: Upload Windows executable
        uses: actions/upload-artifact@v3
        with:
          name: anyGIF-windows
          path: dist/anyGIF.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller ffmpeg-python

      - name: Build Linux executable
        run: |
          pyinstaller --onefile --icon=res/appIcon.ico --collect-all ffmpeg-python -n anyGIF main_linux.py

      - name: Upload Linux executable
        uses: actions/upload-artifact@v3
        with:
          name: anyGIF-linux
          path: dist/anyGIF
